"""The "Annotate" tab: filament tracing, instance editing and per-instance browsing for the active layer.

- Filament layers (and their control layers) get the tracer panel: click control points in 2D, the centreline is
  regenerated by copick core after every edit; New / Reverse / Delete / Convert / Save.
- Instance segmentation layers get the instance editor: paint / erase / fill / pick instance IDs, new ID, recount,
  merge and delete (undoable), save.
- Picks layers can be coloured by instance; panoptic segment layers are browsable.
- The shared instance browser lists the active layer's instances: step, focus, show / hide / isolate.
"""

import logging
from typing import Any, Dict, Optional, Tuple

import numpy as np
from copick_shared_ui.core.types import is_filament_object
from copick_shared_ui.util.filament_session import INSERT_MODE_LABELS, INSERT_MODES, FilamentEditSession
from copick_shared_ui.util.instances import label_bboxes, label_counts, next_instance_id
from copick_shared_ui.widgets.instances import InstanceBrowserWidget
from napari.layers import Image, Labels, Points
from napari.qt.threading import thread_worker
from qtpy.QtCore import Qt, QTimer
from qtpy.QtWidgets import (
    QButtonGroup,
    QCheckBox,
    QComboBox,
    QDialog,
    QDialogButtonBox,
    QFormLayout,
    QGroupBox,
    QHBoxLayout,
    QLabel,
    QLineEdit,
    QMessageBox,
    QPushButton,
    QSpinBox,
    QStackedWidget,
    QVBoxLayout,
    QWidget,
)

from napari_copick.filament_layers import (
    CENTRELINE_KIND,
    CONTROLS_KIND,
    KIND_KEY,
    SESSION_KEY,
    ControlLayerSync,
    add_centreline_layer,
    add_controls_layer,
)
from napari_copick.instance_layers import (
    BBOXES_KEY,
    COUNTS_KEY,
    SEGMENTATION_TYPE_KEY,
    FilamentsAdapter,
    LabelsAdapter,
    PointsAdapter,
    adapter_for,
    instance_colormap,
)

logger = logging.getLogger(__name__)


@thread_worker
def _label_stats_worker(data: np.ndarray):
    return {"counts": label_counts(data), "bboxes": label_bboxes(data)}


@thread_worker
def _label_indices_worker(data: np.ndarray, ids):
    return np.nonzero(np.isin(data, list(ids)))


def _tomogram_layers(viewer: Any):
    return [layer for layer in viewer.layers if isinstance(layer, Image) and "copick_tomogram" in layer.metadata]


class _NewAnnotationDialog(QDialog):
    """Choose run (from an open tomogram), object, user and session for a new filament set or instance seg."""

    def __init__(self, parent: Any, viewer: Any, root: Any, kind: str, user_id: str, session_id: str):
        super().__init__(parent)
        self.setWindowTitle("New filament trace" if kind == "filaments" else "New instance segmentation")
        form = QFormLayout(self)
        self.tomo_combo = QComboBox()
        for layer in _tomogram_layers(viewer):
            self.tomo_combo.addItem(layer.name, layer)
        form.addRow("Tomogram:", self.tomo_combo)
        self.object_combo = QComboBox()
        for obj in root.pickable_objects:
            if kind == "filaments" and not is_filament_object(obj):
                continue
            self.object_combo.addItem(obj.name, obj)
        form.addRow("Object:", self.object_combo)
        self.user_input = QLineEdit(user_id)
        form.addRow("User ID:", self.user_input)
        self.session_input = QLineEdit(session_id)
        form.addRow("Session ID:", self.session_input)
        if kind == "filaments" and self.object_combo.count() == 0:
            note = QLabel("No filament objects. Declare one with ✏️ Edit Objects (check 'Is Filament').")
            note.setWordWrap(True)
            form.addRow(note)
        buttons = QDialogButtonBox(QDialogButtonBox.Ok | QDialogButtonBox.Cancel)
        buttons.accepted.connect(self.accept)
        buttons.rejected.connect(self.reject)
        form.addRow(buttons)
        ok = self.tomo_combo.count() > 0 and self.object_combo.count() > 0
        buttons.button(QDialogButtonBox.Ok).setEnabled(ok)

    def values(self) -> Tuple[Any, Any, str, str]:
        return (
            self.tomo_combo.currentData(),
            self.object_combo.currentData(),
            self.user_input.text().strip() or "napari",
            self.session_input.text().strip() or "manual",
        )


class FilamentTracerPanel(QGroupBox):
    """Controls for one filament session (its centreline + control layers)."""

    def __init__(self, annotate: "AnnotateWidget"):
        super().__init__("〰 Filament tracer")
        self.annotate = annotate
        self.session: Optional[FilamentEditSession] = None
        layout = QVBoxLayout(self)

        self.info = QLabel()
        self.info.setWordWrap(True)
        layout.addWidget(self.info)

        row = QHBoxLayout()
        row.addWidget(QLabel("Active filament:"))
        self.active_spin = QSpinBox()
        self.active_spin.setRange(1, 10_000_000)
        self.active_spin.valueChanged.connect(self._on_active_changed)
        row.addWidget(self.active_spin)
        row.addWidget(QLabel("New points:"))
        self.mode_combo = QComboBox()
        for mode in INSERT_MODES:
            self.mode_combo.addItem(INSERT_MODE_LABELS[mode], mode)
        self.mode_combo.setToolTip(
            "Where a clicked control point goes: after the last, before the first, or into the nearest segment",
        )
        self.mode_combo.currentIndexChanged.connect(lambda _i: self._on_mode_changed(self.mode_combo.currentData()))
        row.addWidget(self.mode_combo)
        layout.addLayout(row)

        buttons = QHBoxLayout()
        self.edit_btn = QPushButton("✏️ Edit")
        self.edit_btn.setCheckable(True)
        self.edit_btn.setToolTip("Show the control points and click in the 2D view to add them")
        self.edit_btn.toggled.connect(self._on_edit_toggled)
        self.new_btn = QPushButton("＋ New")
        self.new_btn.setToolTip("Start a new filament (Shift-N on the control layer)")
        self.new_btn.clicked.connect(self.new_filament)
        self.reverse_btn = QPushButton("⇄ Reverse")
        self.reverse_btn.setToolTip("Reverse the active filament (Shift-R)")
        self.reverse_btn.clicked.connect(lambda: self.reverse(self.active_spin.value()))
        self.delete_btn = QPushButton("🗑 Delete")
        self.delete_btn.setToolTip("Delete the active filament (Shift-D)")
        self.delete_btn.clicked.connect(lambda: self.delete([self.active_spin.value()]))
        for b in (self.edit_btn, self.new_btn, self.reverse_btn, self.delete_btn):
            buttons.addWidget(b)
        layout.addLayout(buttons)

        buttons2 = QHBoxLayout()
        self.convert_btn = QPushButton("Convert to Catmull-Rom")
        self.convert_btn.setToolTip(
            "B-spline fits keep their knots: their handles can be moved but not added or removed.\n"
            "Converting derives Catmull-Rom handles through which points can be added and removed.",
        )
        self.convert_btn.clicked.connect(self.convert_active)
        self.save_btn = QPushButton("💾 Save filaments…")
        self.save_btn.clicked.connect(self.save)
        buttons2.addWidget(self.convert_btn)
        buttons2.addStretch()
        buttons2.addWidget(self.save_btn)
        layout.addLayout(buttons2)

        hint = QLabel(
            "Edit mode: click to add control points (2D view), select + drag to move, Delete to remove. "
            "Shift-N new · Shift-R reverse · Shift-D delete · Shift-] / Shift-[ next / previous.",
        )
        hint.setWordWrap(True)
        hint.setStyleSheet("color: #888; font-size: 10px;")
        layout.addWidget(hint)

    # -- binding ---------------------------------------------------------------------------------------------------

    def set_session(self, session: FilamentEditSession) -> None:
        self.session = session
        self.edit_btn.blockSignals(True)
        self.edit_btn.setChecked(self.annotate.controls_layer(session) is not None)
        self.edit_btn.blockSignals(False)
        self.update_state()

    def update_state(self) -> None:
        s = self.session
        if s is None:
            return
        read_only = s.read_only
        n = len(s.to_list())
        dirty = " · unsaved changes" if s.dirty else ""
        note = " · read-only source (save under a user session)" if read_only else ""
        self.info.setText(
            f"<b>{s.object_name}</b> ({s.user_id} | {s.session_id}) · run {s.run.name} · {n} filaments · "
            f"step {s.step:g} Å{dirty}{note}",
        )
        self.active_spin.blockSignals(True)
        self.active_spin.setValue(s.active_id)
        self.active_spin.blockSignals(False)
        self.mode_combo.blockSignals(True)
        self.mode_combo.setCurrentIndex(max(0, self.mode_combo.findData(s.insert_mode)))
        self.mode_combo.blockSignals(False)
        kind = s.kind(s.active_id)
        self.convert_btn.setVisible(kind == "bspline")

    # -- actions ---------------------------------------------------------------------------------------------------

    def _on_active_changed(self, value: int) -> None:
        if self.session is not None:
            self.session.active_id = int(value)
            controls = self.annotate.controls_layer(self.session)
            if controls is not None:
                controls.feature_defaults = {"instance_id": int(value), "order": -1}
            self.update_state()
            self.annotate.browser.set_current(int(value), emit=False)

    def _on_mode_changed(self, mode: str) -> None:
        if self.session is not None:
            self.session.insert_mode = mode

    def _on_edit_toggled(self, on: bool) -> None:
        if self.session is None:
            return
        if on:
            self.annotate.start_editing(self.session)
        else:
            self.annotate.stop_editing(self.session)

    def new_filament(self) -> None:
        if self.session is None:
            return
        self.session.new_filament()
        self.annotate.after_session_edit(self.session)

    def reverse(self, instance_id: int) -> None:
        if self.session is None:
            return
        self.session.reverse(instance_id)
        self.annotate.after_session_edit(self.session)

    def join(self, ids, target: int) -> None:
        if self.session is None:
            return
        try:
            self.session.join(ids, target=target)
        except ValueError as e:
            logger.warning(str(e))
            return
        self.annotate.after_session_edit(self.session)

    def delete(self, ids) -> None:
        if self.session is None:
            return
        for i in ids:
            self.session.delete_filament(int(i))
        self.annotate.after_session_edit(self.session)

    def convert_active(self) -> None:
        if self.session is None:
            return
        self.session.convert_to_catmull_rom(self.session.active_id)
        self.annotate.after_session_edit(self.session)

    def step(self, delta: int) -> None:
        if self.session is None:
            return
        ids = self.session.ids()
        if not ids:
            return
        i = ids.index(self.session.active_id) if self.session.active_id in ids else -1
        self.session.active_id = ids[(i + delta) % len(ids)]
        self.annotate.after_session_edit(self.session, focus=True)

    def save(self) -> None:
        if self.session is None:
            return
        layer = self.annotate.centreline_layer(self.session) or self.annotate.controls_layer(self.session)
        self.annotate.plugin.save_manager.open_save_filaments_dialog(preset_layer=layer)


class InstanceEditorPanel(QGroupBox):
    """Controls for painting instance IDs into a labels layer."""

    def __init__(self, annotate: "AnnotateWidget"):
        super().__init__("🖌 Instance editor")
        self.annotate = annotate
        self.layer: Optional[Labels] = None
        layout = QVBoxLayout(self)
        self.info = QLabel()
        self.info.setWordWrap(True)
        layout.addWidget(self.info)
        self.warning = QLabel()
        self.warning.setWordWrap(True)
        self.warning.setStyleSheet("color: #d08000; font-size: 11px;")
        layout.addWidget(self.warning)

        form = QFormLayout()
        id_row = QHBoxLayout()
        self.id_spin = QSpinBox()
        self.id_spin.setRange(0, 2**31 - 1)
        self.id_spin.valueChanged.connect(self._on_id_changed)
        id_row.addWidget(self.id_spin)
        self.new_id_btn = QPushButton("＋ New ID")
        self.new_id_btn.clicked.connect(self.new_id)
        id_row.addWidget(self.new_id_btn)
        form.addRow("Instance ID:", id_row)
        self.brush_spin = QSpinBox()
        self.brush_spin.setRange(1, 500)
        self.brush_spin.valueChanged.connect(self._on_brush_changed)
        form.addRow("Brush size:", self.brush_spin)
        self.preserve_cb = QCheckBox("Paint only background (keep other instances)")
        self.preserve_cb.toggled.connect(self._on_preserve_changed)
        form.addRow("", self.preserve_cb)
        layout.addLayout(form)

        modes = QHBoxLayout()
        self.mode_group = QButtonGroup(self)
        for mode, text, tip in (
            ("paint", "🖌 Paint", "Paint the current ID"),
            ("erase", "🧽 Erase", "Erase to background"),
            ("fill", "🪣 Fill", "Fill a connected region with the current ID"),
            ("pick", "🎯 Pick", "Click a voxel to make its ID current"),
            ("pan_zoom", "✋ View", "Pan and zoom"),
        ):
            b = QPushButton(text)
            b.setCheckable(True)
            b.setToolTip(tip)
            b.setProperty("mode", mode)
            self.mode_group.addButton(b)
            modes.addWidget(b)
        self.mode_group.buttonClicked.connect(lambda b: self._set_mode(b.property("mode")))
        layout.addLayout(modes)

        actions = QHBoxLayout()
        self.recount_btn = QPushButton("↻ Recount")
        self.recount_btn.setToolTip("Recompute the instance list (voxel counts and bounding boxes)")
        self.recount_btn.clicked.connect(self.recount)
        self.save_btn = QPushButton("💾 Save instances…")
        self.save_btn.clicked.connect(self.save)
        actions.addWidget(self.recount_btn)
        actions.addStretch()
        actions.addWidget(self.save_btn)
        layout.addLayout(actions)

    def set_layer(self, layer: Labels) -> None:
        if self.layer is not None:
            try:
                self.layer.events.selected_label.disconnect(self._sync_from_layer)
                self.layer.events.mode.disconnect(self._sync_from_layer)
            except (TypeError, ValueError, RuntimeError):
                pass
        self.layer = layer
        layer.events.selected_label.connect(self._sync_from_layer)
        layer.events.mode.connect(self._sync_from_layer)
        self._sync_from_layer()

    def _sync_from_layer(self, *_args) -> None:
        layer = self.layer
        if layer is None:
            return
        meta = layer.metadata
        counts = meta.get(COUNTS_KEY, {})
        level = meta.get("copick_resolution_level", 0) or 0
        obj = meta.get("copick_source_object_name", "?")
        seg = meta.get("copick_segmentation")
        origin = f"{seg.user_id} | {seg.session_id}" if seg is not None else "new, unsaved"
        self.info.setText(f"<b>{obj}</b> ({origin}) · {len(counts)} instances · {layer.data.dtype}")
        self.warning.setText(
            (
                f"Loaded at resolution level {level}: saving upsamples it to full resolution with nearest-neighbour "
                "interpolation, so painted edges come out blocky. Load level 0 to edit at full resolution."
                if level
                else ""
            ),
        )
        self.warning.setVisible(bool(level))
        for w, v in ((self.id_spin, int(layer.selected_label)), (self.brush_spin, int(layer.brush_size))):
            w.blockSignals(True)
            w.setValue(v)
            w.blockSignals(False)
        self.preserve_cb.blockSignals(True)
        self.preserve_cb.setChecked(bool(layer.preserve_labels))
        self.preserve_cb.blockSignals(False)
        mode = str(getattr(layer.mode, "value", layer.mode))
        for b in self.mode_group.buttons():
            b.setChecked(b.property("mode") == mode)

    def _on_id_changed(self, value: int) -> None:
        if self.layer is not None:
            self._ensure_capacity(value)
            self.layer.selected_label = int(value)
            self._ensure_colored(int(value))
            self.annotate.browser.set_current(int(value), emit=False)

    def _on_brush_changed(self, value: int) -> None:
        if self.layer is not None:
            self.layer.brush_size = int(value)

    def _on_preserve_changed(self, on: bool) -> None:
        if self.layer is not None:
            self.layer.preserve_labels = bool(on)

    def _set_mode(self, mode: str) -> None:
        if self.layer is not None:
            self.layer.mode = mode

    def _ensure_capacity(self, value: int) -> None:
        """Instance IDs above 65535 need a uint32 volume."""
        layer = self.layer
        dtype = layer.data.dtype
        if dtype.kind in "ui" and value > np.iinfo(dtype).max:
            layer.data = layer.data.astype(np.uint32)

    def _ensure_colored(self, value: int) -> None:
        counts = self.layer.metadata.setdefault(COUNTS_KEY, {})
        known = set(counts) | self.layer.metadata.setdefault("copick_extra_ids", set())
        if value > 0 and value not in known:
            self.layer.metadata["copick_extra_ids"].add(value)
            ids = set(counts) | self.layer.metadata["copick_extra_ids"]
            self.layer.colormap = instance_colormap(ids, self.layer.metadata.get("copick_hidden_ids", ()))

    def new_id(self) -> None:
        if self.layer is None:
            return
        counts = self.layer.metadata.get(COUNTS_KEY, {})
        value = next_instance_id(counts.keys(), self.layer.metadata.get("copick_extra_ids", set()))
        self.id_spin.setValue(value)
        self._set_mode("paint")

    def recount(self) -> None:
        layer = self.layer
        if layer is None:
            return
        worker = _label_stats_worker(np.asarray(layer.data))

        def done(result: Dict[str, Any]) -> None:
            layer.metadata[COUNTS_KEY] = result["counts"]
            layer.metadata[BBOXES_KEY] = result["bboxes"]
            layer.metadata["copick_extra_ids"] = set()
            layer.colormap = instance_colormap(result["counts"].keys(), layer.metadata.get("copick_hidden_ids", ()))
            self._sync_from_layer()
            self.annotate.refresh()

        worker.returned.connect(done)
        worker.start()

    def relabel(self, ids, value: int) -> None:
        """Set ``ids`` to ``value`` (0 deletes) through the layer, so the edit can be undone."""
        layer = self.layer
        if layer is None:
            return
        worker = _label_indices_worker(np.asarray(layer.data), ids)

        def done(indices) -> None:
            if len(indices[0]):
                layer.data_setitem(indices, value)
            self.recount()

        worker.returned.connect(done)
        worker.start()

    def save(self) -> None:
        if self.layer is not None:
            self.annotate.viewer.layers.selection.active = self.layer
            self.annotate.plugin.save_manager.open_save_segmentation_dialog()


class AnnotateWidget(QWidget):
    """The Annotate tab."""

    def __init__(self, viewer: Any, plugin: Any):
        super().__init__()
        self.viewer = viewer
        self.plugin = plugin
        self._syncs: Dict[int, Tuple[ControlLayerSync, Any]] = {}  # id(session) -> (sync, controls layer)
        self._adapter = None

        layout = QVBoxLayout(self)
        layout.setContentsMargins(4, 4, 4, 4)
        self.active_label = QLabel()
        self.active_label.setWordWrap(True)
        layout.addWidget(self.active_label)

        start = QHBoxLayout()
        self.new_trace_btn = QPushButton("〰 New filament trace…")
        self.new_trace_btn.clicked.connect(self.new_trace)
        self.new_instances_btn = QPushButton("🖌 New instance segmentation…")
        self.new_instances_btn.clicked.connect(self.new_instance_segmentation)
        start.addWidget(self.new_trace_btn)
        start.addWidget(self.new_instances_btn)
        layout.addLayout(start)

        self.stack = QStackedWidget()
        self.empty = QLabel(
            "Select a picks, filaments or instance segmentation layer, or start a new trace or instance "
            "segmentation. Load filaments and segmentations from the tree (right-click for editing actions).",
        )
        self.empty.setWordWrap(True)
        self.empty.setAlignment(Qt.AlignTop)
        self.empty.setStyleSheet("color: #888;")
        self.tracer = FilamentTracerPanel(self)
        self.editor = InstanceEditorPanel(self)
        self.stack.addWidget(self.empty)
        self.stack.addWidget(self.tracer)
        self.stack.addWidget(self.editor)
        layout.addWidget(self.stack)

        self.browser = InstanceBrowserWidget(title="Instances")
        self.browser.current_changed.connect(self._on_browser_current)
        self.browser.focus_requested.connect(self._on_browser_focus)
        self.browser.visibility_changed.connect(self._on_browser_visibility)
        self.browser.new_requested.connect(self._on_browser_new)
        self.browser.delete_requested.connect(self._on_browser_delete)
        self.browser.merge_requested.connect(self._on_browser_merge)
        self.browser.reverse_requested.connect(self._on_browser_reverse)
        self.browser.color_by_instance_toggled.connect(self._on_color_toggle)
        layout.addWidget(self.browser, 1)

        viewer.layers.selection.events.active.connect(self._on_active_layer)
        viewer.layers.events.removed.connect(self._on_layer_removed)
        # napari activates a new layer before its creator has filled in the copick metadata; look again afterwards.
        viewer.layers.events.inserted.connect(lambda _event: QTimer.singleShot(0, self._on_active_layer))
        self._on_active_layer()

    # -- layers of a session ---------------------------------------------------------------------------------------

    def _session_layers(self, session: FilamentEditSession, kind: str):
        for layer in self.viewer.layers:
            if layer.metadata.get(SESSION_KEY) is session and layer.metadata.get(KIND_KEY) == kind:
                return layer
        return None

    def centreline_layer(self, session: FilamentEditSession):
        return self._session_layers(session, CENTRELINE_KIND)

    def controls_layer(self, session: FilamentEditSession):
        return self._session_layers(session, CONTROLS_KIND)

    def start_editing(self, session: FilamentEditSession) -> None:
        """Show the control layer of a session and switch it to add mode."""
        centreline = self.centreline_layer(session)
        if centreline is None:
            centreline = add_centreline_layer(self.viewer, session)
        controls = self.controls_layer(session)
        if controls is None:
            controls = add_controls_layer(self.viewer, session)
            sync = ControlLayerSync(controls, centreline, session, on_change=lambda msg: self._after_sync(session, msg))
            controls.events.data.connect(sync.on_data_event)
            self._syncs[id(session)] = (sync, controls)
            self._bind_keys(controls)
        if self.viewer.dims.ndisplay != 2:
            self.plugin.info_label.setText("Switch to the 2D view to place control points.")
        self.viewer.layers.selection.active = controls
        controls.mode = "add"

    def stop_editing(self, session: FilamentEditSession) -> None:
        controls = self.controls_layer(session)
        if controls is not None:
            self.viewer.layers.remove(controls)
        centreline = self.centreline_layer(session)
        if centreline is not None:
            self.viewer.layers.selection.active = centreline

    def _bind_keys(self, layer: Points) -> None:
        bindings = {
            "Shift-N": lambda _layer: self.tracer.new_filament(),
            "Shift-R": lambda _layer: self.tracer.reverse(self.tracer.active_spin.value()),
            "Shift-D": lambda _layer: self.tracer.delete([self.tracer.active_spin.value()]),
            "Shift-]": lambda _layer: self.tracer.step(1),
            "Shift-[": lambda _layer: self.tracer.step(-1),
        }
        for key, func in bindings.items():
            try:
                layer.bind_key(key, func, overwrite=True)
            except Exception as e:  # pragma: no cover - depends on the napari version
                logger.warning(f"Could not bind {key}: {e}")

    def _after_sync(self, session: FilamentEditSession, message: str) -> None:
        if message:
            self.plugin.info_label.setText(message)
        self.tracer.update_state()
        self.refresh()

    def after_session_edit(self, session: FilamentEditSession, focus: bool = False) -> None:
        """Redraw a session's layers after an edit made through the panel or browser."""
        entry = self._syncs.get(id(session))
        if entry is not None and entry[1] in self.viewer.layers:
            entry[0].redraw()
        else:
            centreline = self.centreline_layer(session)
            if centreline is not None:
                from napari_copick.filament_layers import refresh_centreline_layer

                refresh_centreline_layer(centreline, session)
        self.tracer.update_state()
        self.refresh()
        if focus and isinstance(self._adapter, FilamentsAdapter):
            self._adapter.focus(session.active_id)

    # -- starting new annotations ----------------------------------------------------------------------------------

    def _new_dialog(self, kind: str):
        if self.plugin.root is None:
            self.plugin.info_label.setText("Load a configuration first.")
            return None
        if not _tomogram_layers(self.viewer):
            self.plugin.info_label.setText("Open a tomogram first (the new annotation uses its run and voxel spacing).")
            return None
        sm = self.plugin.save_manager
        dlg = _NewAnnotationDialog(
            self,
            self.viewer,
            self.plugin.root,
            kind,
            sm._last_user_id or "napari",
            sm._last_session_id or "manual",
        )
        if dlg.exec_() != QDialog.Accepted:
            return None
        return dlg.values()

    def new_trace(self) -> None:
        values = self._new_dialog("filaments")
        if values is None:
            return
        tomo_layer, obj, user_id, session_id = values
        vs = tomo_layer.metadata["copick_voxel_spacing"]
        session = FilamentEditSession(vs.run, obj.name, user_id, session_id, step=vs.voxel_size)
        add_centreline_layer(self.viewer, session)
        self.start_editing(session)
        self.tracer.set_session(session)
        self.stack.setCurrentWidget(self.tracer)

    def open_filaments(self, copick_filaments: Any) -> None:
        """Load a filament set (if not loaded) and start editing it."""
        for layer in self.viewer.layers:
            if layer.metadata.get("copick_filaments") is copick_filaments:
                self.start_editing(layer.metadata[SESSION_KEY])
                return
        session = FilamentEditSession.from_filaments(copick_filaments, step=copick_filaments.voxel_spacing or 10.0)
        layer = add_centreline_layer(self.viewer, session, run=copick_filaments.run)
        layer.metadata["copick_filaments"] = copick_filaments
        self.start_editing(session)

    def new_instance_segmentation(self) -> None:
        values = self._new_dialog("instance")
        if values is None:
            return
        tomo_layer, obj, user_id, session_id = values
        shape = tomo_layer.data.shape[-3:]
        layer = self.viewer.add_labels(
            np.zeros(shape, dtype=np.uint16),
            name=f"Instances: {obj.name} ({user_id} | {session_id}) (new)",
            scale=tomo_layer.scale[-3:],
        )
        vs = tomo_layer.metadata["copick_voxel_spacing"]
        layer.metadata.update(
            {
                "copick_run": vs.run,
                "copick_voxel_size": vs.voxel_size,
                "copick_resolution_level": tomo_layer.metadata.get("copick_resolution_level", 0),
                "copick_source_object_name": obj.name,
                SEGMENTATION_TYPE_KEY: "instance",
                COUNTS_KEY: {},
                BBOXES_KEY: {},
            },
        )
        layer.colormap = instance_colormap([1])
        layer.metadata["copick_extra_ids"] = {1}
        layer.selected_label = 1
        layer.mode = "paint"
        self.viewer.layers.selection.active = layer

    # -- active layer ----------------------------------------------------------------------------------------------

    def _on_layer_removed(self, event: Any) -> None:
        layer = getattr(event, "value", None)
        session = layer.metadata.get(SESSION_KEY) if layer is not None else None
        if session is not None and layer.metadata.get(KIND_KEY) == CONTROLS_KIND:
            self._syncs.pop(id(session), None)
            if self.tracer.session is session:
                self.tracer.edit_btn.blockSignals(True)
                self.tracer.edit_btn.setChecked(False)
                self.tracer.edit_btn.blockSignals(False)
        if self._adapter is not None and self._adapter.layer is layer:
            self._adapter = None
            self._on_active_layer()

    def _on_active_layer(self, *_args) -> None:
        layer = self.viewer.layers.selection.active
        session = layer.metadata.get(SESSION_KEY) if layer is not None else None
        if session is not None:
            centreline = self.centreline_layer(session)
            self._adapter = FilamentsAdapter(centreline, self.viewer) if centreline is not None else None
            self.tracer.set_session(session)
            self.stack.setCurrentWidget(self.tracer)
        else:
            self._adapter = adapter_for(layer, self.viewer)
            if isinstance(self._adapter, LabelsAdapter):
                self.editor.set_layer(layer)
                self.stack.setCurrentWidget(self.editor)
            else:
                self.stack.setCurrentWidget(self.empty)
        self.active_label.setText(f"Active layer: <b>{layer.name}</b>" if layer is not None else "No active layer")
        caps = dict(self._adapter.capabilities) if self._adapter is not None else {}
        self.browser.set_capabilities(**caps)
        if isinstance(self._adapter, PointsAdapter):
            self.browser.set_color_by_instance(layer.metadata.get("copick_color_mode") == "instance")
        self.refresh(reset=True)

    def refresh(self, reset: bool = False) -> None:
        if self._adapter is None:
            self.browser.set_title("Instances")
            self.browser.clear()
            return
        self.browser.set_title(self._adapter.title)
        if reset:
            self.browser.clear()
        self.browser.set_rows(self._adapter.rows(), kind=self._adapter.kind)

    # -- browser actions -------------------------------------------------------------------------------------------

    def _on_browser_current(self, key: int) -> None:
        if isinstance(self._adapter, FilamentsAdapter):
            self.tracer.active_spin.setValue(key)
        elif isinstance(self._adapter, LabelsAdapter):
            self.editor.id_spin.setValue(key)

    def _on_browser_focus(self, key: int) -> None:
        if self._adapter is not None:
            self._adapter.focus(key)

    def _on_browser_visibility(self, keys) -> None:
        if self._adapter is not None:
            self._adapter.set_visible(set(keys))

    def _on_browser_new(self) -> None:
        if isinstance(self._adapter, FilamentsAdapter):
            self.tracer.new_filament()
        elif isinstance(self._adapter, LabelsAdapter):
            self.editor.new_id()

    def _on_browser_delete(self, keys) -> None:
        if not keys:
            return
        reply = QMessageBox.question(
            self,
            "Delete instances",
            f"Delete {len(keys)} instance(s)? (Instance segmentation edits can be undone with Ctrl-Z.)",
            QMessageBox.Yes | QMessageBox.No,
            QMessageBox.No,
        )
        if reply != QMessageBox.Yes:
            return
        if isinstance(self._adapter, FilamentsAdapter):
            self.tracer.delete(keys)
        elif isinstance(self._adapter, LabelsAdapter):
            self.editor.relabel(keys, 0)

    def _on_browser_merge(self, sources, target: int) -> None:
        if isinstance(self._adapter, LabelsAdapter):
            self.editor.relabel(sources, target)
        elif isinstance(self._adapter, FilamentsAdapter):
            self.tracer.join([target, *sources], target)

    def _on_browser_reverse(self, key: int) -> None:
        if isinstance(self._adapter, FilamentsAdapter):
            self.tracer.reverse(key)

    def _on_color_toggle(self, on: bool) -> None:
        if isinstance(self._adapter, PointsAdapter):
            self._adapter.set_color_by_instance(on)
